---
title: "Historical analysis of the CRAN package network"
author: "[Ioannis Kosmidis](https://www.ikosmidis.com)"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Historical analysis of the CRAN package network}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---


```{r}
dates <- seq.Date(as.Date("2018-12-01"), as.Date("2019-07-19"), by = 1)
```

Download package files
```{r}
target_directory <- "~/Downloads/packages/"
base_url <- "https://cran.microsoft.com/snapshot/"
suffix <- "/src/contrib/PACKAGES.rds"
for (j in seq_along(dates)) {
    d <- dates[j]
    cat(format(d), "\n")
    d_url <- paste0(base_url, format(d), suffix, collapse = "/")
    target_file <- paste0(target_directory, paste0("PACKAGES-", format(d), ".rds"), collapse = "/")
    res <- try(download.file(d_url, target_file))
    if (inherits(res, "try-error")) next
}
```

Dynamic network visualisations [here](https://curleylab.psych.columbia.edu/netviz/) and [here](https://kateto.net/network-visualization)


Clean up all files
```{r}
library("cranly")
library("parallel")
files <- dir("~/Downloads/packages", full.name = TRUE)
# cleaned_data <- NULL
# for (f in files) {
#     p_db <- readRDS(f)
#     cleaned_data[[f]] <- clean_CRAN_db(p_db)
#     cat(f, "\n")
# }
cleaned_data <- mclapply(files, function(f) {
  cat(f, "\n")
  p_db <- readRDS(f)
  clean_CRAN_db(p_db)
}, mc.cores = 4)
```

Quick plots
```{r}
library("cranly")
package_db <- clean_CRAN_db()
package_db |> build_network(perspective = "package") |> plot(package = "brglm")
package_db |> build_network(perspective = "author") |> plot(author = "Ioannis Kosmidis")
```

Summaries excluding base
```{r}
library("cranly")
package_db <- clean_CRAN_db()
package_network <- build_network(package_db)
optional_packages <- subset(package_network, recommended = FALSE, base = FALSE)
optional_summary <- summary(optional_packages)
plot(optional_summary, top = 30, according_to = "n_imported_by")
```


`cran_sample`
```{r}
library(cranly)
p_db <- tools::CRAN_package_db()
package_db <- clean_CRAN_db(p_db)
set.seed(333)
cran_sample <- package_db[sample(seq.int(nrow(p_db)), 1000, replace = FALSE), ]
```

Dependence trees
```{r}
library("cranly")
p_db <- tools::CRAN_package_db()
package_db <- clean_CRAN_db(p_db)
package_network <- build_network(package_db)
## tidyverse dependence tree with legend and title
tidyverse_tree <- build_dependence_tree(package_network, package = "tidyverse")
plot(tidyverse_tree, , legend = TRUE, title = TRUE)
## tibble dependence tree
tibble_tree <- build_dependence_tree(package_network, package = "tibble")
plot(tibble_tree)
## PlackettLuce dependence tree excluding base and recommended packages
pl_tree <- build_dependence_tree(package_network, package = "PlackettLuce")
plot(pl_tree, base = FALSE, recommended = FALSE)
```










```{r}
library("ggraph")
library("cranly")
library("tidygraph")
library("gganimate")

p_db <- tools::CRAN_package_db()
package_db <- clean_CRAN_db(p_db)
package_network <- build_network(package_db)

ii <- subset(package_network, package = "brglm2")

gr <- as.igraph(ii)
ggraph(gr, layout = 'igraph', algorithm = "nicely") +
    geom_node_point() +
    geom_node_label(aes(label = name, vjust = -0.3), alpha = 0) +
    geom_edge_link() +
    theme_void()
```






```{r}
library("ggraph")
library("cranly")
library("tidygraph")
library("gganimate")
library("parallel")

load("~/Downloads/package_database.rda")

package_networks <- mclapply(seq_along(cleaned_data), function(f) {
    cat(files[f], "\n")
    build_network(cleaned_data[[f]])
}, mc.cores = 4)

tidyverse_networks <- mclapply(seq_along(cleaned_data), function(f) {
    ss <- subset(package_networks[[f]], package = "tidyverse")$edges
    ss$date <- dates[f]
    cat(f, "\n")
    ss
}, mc.cores = 4)


edges <- do.call("rbind", tidyverse_networks)
## edges <- edges[seq(1, nrow(edges), 10), ]
edges <- subset(edges, type = "depends")
edge_levels <- with(edges, unique(c(from, to)))
edges$from <- as.numeric(factor(edges$from, levels = edge_levels))
edges$to <- as.numeric(factor(edges$to, levels = edge_levels))
nodes <- data.frame(nodes = factor(edge_levels, levels = edge_levels), name = edge_levels)
gr <- tbl_graph(nodes = nodes, edges = edges, directed = TRUE) |> 
        mutate(degree = centrality_degree())

fade_edge <- function(x) {
        x$edge_alpha = 0
        x$edge_width = 0
        x
}

## Animation Code
p <- ggraph(gr, 'lgl') +
    geom_edge_link0(aes(color = type), edge_width = 0.5, edge_alpha = 1,
                    arrow = grid::arrow(length = unit(0.1, "cm"))) +
    geom_node_label(aes(label = name), label.padding = unit(0.05, "cm")) +
    geom_node_point(aes(size = degree), colour = '#1B2733', show.legend = FALSE) +
    scale_size_area(max_size = 4) +
    theme_graph() +
    ## theme(plot.background = element_rect(fill = '#B5C9BA'), plot.title = element_text(color = '#F77976')) +
    ggtitle('tibble network', subtitle = 'Date: {format(frame_time, "%Y-%m-%d")}') +
    transition_time(date)
## enter_manual(fade_edge) +
## exit_manual(fade_edge)

animate(p, 700, 5, renderer = ffmpeg_renderer())


 ```



